"use client";

import Link from "next/link";
import { useState } from "react";
import {
  useMutation,
  useQuery,
  useQueryClient,
} from "@tanstack/react-query";
import jsPDF from "jspdf";

import apiRouter from "@/api/router";
import type { TaxSubmission } from "@/api/tax-submission";

export default function TaxSubmissionsPage() {
  const [search, setSearch] = useState("");
  const queryClient = useQueryClient();

  const { data: submissions = [], isLoading } = useQuery<TaxSubmission[]>({
    queryKey: ["getTaxSubmissions"],
    queryFn: apiRouter.taxSubmissions.getTaxSubmissions,
  });

  const deleteMutation = useMutation({
    mutationFn: (id: number) =>
      apiRouter.taxSubmissions.deleteTaxSubmission(id),

    onSuccess: () => {
      alert("Submission berhasil dihapus.");

      queryClient.invalidateQueries({
        queryKey: ["getTaxSubmissions"],
      });
    },
  });

  const downloadPdf = (item: TaxSubmission) => {
  const doc = new jsPDF();

  doc.setFontSize(22);
  doc.text("SMART CORE PAJAK", 105, 20, {
    align: "center",
  });

  doc.setFontSize(13);
  doc.text("Tax Submission Report", 105, 30, {
    align: "center",
  });

  doc.line(20, 38, 190, 38);

  let y = 50;

  const addRow = (label: string, value: string) => {
    doc.setFont("helvetica", "bold");
    doc.text(label, 20, y);

    doc.setFont("helvetica", "normal");
    doc.text(value, 70, y);

    y += 12;
  };

  addRow("Submission ID", String(item.id));
  addRow("Tax Service", item.tax_service.name);
  addRow("Taxpayer", item.taxpayer_name);
  addRow("NPWP", item.npwp);
  addRow("Fiscal Year", String(item.fiscal_year));
  addRow(
    "Amount",
    "Rp " + Number(item.amount).toLocaleString("id-ID")
  );
  addRow("Status", item.status);

  addRow(
  "Submitted Time",
  new Date(item.created_at).toLocaleString("id-ID")
);

  if (item.status === "Approved") {
    addRow(
      "Approved Time",
      new Date(item.updated_at).toLocaleString("id-ID")
    );
  }

  if (item.status === "Rejected") {
    addRow(
      "Rejected Time",
      new Date(item.updated_at).toLocaleString("id-ID")
    );
  }

  if (item.status === "Pending") {
    addRow(
      "Submitted Time",
      new Date(item.created_at).toLocaleString("id-ID")
    );
  }

  doc.line(20, y + 5, 190, y + 5);

  doc.setFontSize(10);
  doc.text(
    "Generated by Smart Core Pajak",
    105,
    y + 18,
    {
      align: "center",
    }
  );

  doc.save(`Submission-${item.id}.pdf`);
};

  const filtered = submissions.filter(
    (item) =>
      item.taxpayer_name
        .toLowerCase()
        .includes(search.toLowerCase()) ||
      item.npwp
        .toLowerCase()
        .includes(search.toLowerCase()) ||
      item.tax_service.name
        .toLowerCase()
        .includes(search.toLowerCase())
  );

  return (
    <section className="min-h-screen bg-slate-100 p-8">
      <div className="mx-auto mt-16 max-w-7xl">

        <div className="mb-8 flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-black">
              Tax Submissions
            </h1>

            <p className="mt-2 text-slate-500">
              Semua laporan pajak yang dikirim user.
            </p>
          </div>

          <input
            type="text"
            placeholder="Cari..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="w-72 rounded-xl border p-3"
          />
        </div>

        <div className="overflow-hidden rounded-3xl bg-white shadow">
          <table className="w-full">
            <thead className="bg-slate-950 text-white">
              <tr>
                <th className="p-4">ID</th>
                <th className="p-4">Service</th>
                <th className="p-4">Taxpayer</th>
                <th className="p-4">NPWP</th>
                <th className="p-4">Fiscal Year</th>
                <th className="p-4">Amount</th>
                <th className="p-4">Submitted At</th>
                <th className="p-4">Status</th>
                <th className="p-4">Action</th>
              </tr>
            </thead>

            <tbody>
              {isLoading ? (
                <tr>
                  <td
                    colSpan={8}
                    className="p-8 text-center"
                  >
                    Loading...
                  </td>
                </tr>
              ) : filtered.length > 0 ? (
                filtered.map((item) => (
                  <tr
                    key={item.id}
                    className="border-b"
                  >
                    <td className="p-4">{item.id}</td>

                    <td className="p-4">
                      {item.tax_service.name}
                    </td>

                    <td className="p-4">
                      {item.taxpayer_name}
                    </td>

                    <td className="p-4">
                      {item.npwp}
                    </td>

                    <td className="p-4">
                      {item.fiscal_year}
                    </td>

                    <td className="p-4">
                      Rp {Number(item.amount).toLocaleString("id-ID")}
                    </td>

                    <td className="p-4">
                      {new Date(item.created_at).toLocaleString("id-ID", {
                        dateStyle: "medium",
                        timeStyle: "short",
                      })}
                    </td>

                    <td className="p-4">
                      {item.status}
                    </td>

                    <td className="p-4">
                      <div className="flex justify-center gap-2">

                        <button
                          onClick={() => downloadPdf(item)}
                          className="rounded-xl bg-cyan-600 px-4 py-2 text-white hover:bg-cyan-700"
                        >
                          PDF
                        </button>

                        <Link
                          href={`/admin/tax-submissions/edit/${item.id}`}
                          className="rounded-xl bg-amber-500 px-4 py-2 text-white"
                        >
                          Edit
                        </Link>

                        <button
                          onClick={() =>
                            deleteMutation.mutate(item.id)
                          }
                          className="rounded-xl bg-red-600 px-4 py-2 text-white"
                        >
                          Delete
                        </button>
                      </div>
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td
                    colSpan={8}
                    className="p-8 text-center"
                  >
                    Belum ada submission.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>

      </div>
    </section>
  );
}